apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vuln
  template:
    metadata:
      labels:
        app: vuln
    spec:
      containers:
      - name: app
        image: nginx:latest
        securityContext:
          privileged: true
        env:
        - name: DB_PASSWORD
          value: "plaintextpassword"
